name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
      PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      # Upload HTML report
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 30

      # Upload videos
      - name: Upload Playwright videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-videos-${{ matrix.os }}
          path: test-results/**/*.webm
          retention-days: 30

      # Upload screenshots
      - name: Upload Playwright screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-screenshots-${{ matrix.os }}
          path: test-results/**/*.png
          retention-days: 30

      # Upload traces
      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces-${{ matrix.os }}
          path: test-results/**/*.zip
          retention-days: 30